### PR TITLE
Added the airbnb rules and basic jsdoc

### PR DESCRIPTION
**Pull request by vladimirsan**

### CODE REVIEW

**Comment by vladimirsan** [comment]
I also removed the C# code in the repo because I realized while teaching LEAP that my C# was very outdated...

**Comment by vladimirsan** [comment]
I'm closing it because I discovered that jsdoc is heavily impaired when talking about javascript...

**Comment by vladimirsan** [comment]
OK we are back on track. I fixed the documentation and the named conventions of my linked list class.

**Review by bgwest — COMMENTED** [review]
hey @vladimirsan I have tried to re-compile your docs locally a couple different ways. Once with jsdocs and a config.json that is setup for type script and once with the @microsoft/tsdoc playground. I am getting parsing errors on both. It could definitely be how I am doing it, but If you can detail out how you are compiling your docs I can re-run it locally if you'd like to test for valid syntax again. Since the major changes were removing the C# and adding the docs I figured that would be a good check. Please let me know your thoughts.

**Comment by vladimirsan** [comment]
Thanks ben! I'm not using jsdocs haha!

**Pull request merged**
